---
- name: create local apt conf
  file: 
    path: /etc/apt/apt.conf.d/99local
    owner: root
    group: root
    state: touch
    
- name: disable install recommends
  lineinfile:
    path: /etc/apt/apt.conf.d/99local
    line: 'APT::Install-Recommends "false";'
    state: present
    
- name: disable install suggestions
  lineinfile:
    path: /etc/apt/apt.conf.d/99local
    line: 'APT::Install-Suggests "false";'
    state: present

    
- name: remove login info
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/issue.net
    - /etc/issue
    
- name: upgrade packages
  apt:
    upgrade: dist
    
- name: remove unneeded packages
  apt:
    pkg:
    - linux-image-*
    - linux-headers-*
    - apache2
    - apache2-bin
    - apache2-data
    - apache2-utils
    - hostapd
    - libgtk3-common
    state: absent
    autoremove: yes

- name: update RCN scripts
  command:
    chdir: /opt/scripts
    cmd: 'git pull'

- name: install debconf-utils and curl
  apt:
    pkg: 
      - debconf-utils
      - curl
    state: present

- name: update package list
  apt:
    update_cache: yes

- name: install packages
  apt:
    pkg:
    - unzip
    - iptables
    - iptables-persistent
    - python-pip
    - python3-pip
    - python-dev
    - libavahi-compat-libdnssd1
    - libnss-mdns
    - byobu
    - htop
    - unzip
    - cpufrequtils
    - pkg-config
    - python3-dev
    - pkg-config
    state: present
    autoremove: yes
    autoclean: yes

- name: enable netfilter
  service:
    name: netfilter-persistent
    enabled: yes

- name: enable root login via ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'PermitRootLogin yes'
    state: present

- name: disable the power button
  lineinfile:
    path: /etc/systemd/logind.conf
    line: 'HandlePowerKey=ignore'
    state: present

#- name: disable wireless power management
#  file:
#    path: /etc/pm/sleep.d/wireless
#    state: touch

#- name: update dhcp
#  lineinfile:
#    path: /etc/NetworkManager/NetworkManager.conf
#    line: 'dhcp=internal'
#    insertafter: '[main]'
#    state: present

#- name: setup network interfaces file
#  blockinfile:
#    path: /etc/network/interfaces
#    create: yes
#    block: |
      # This file describes the network interfaces available on your system
      # and how to activate them. For more information, see interfaces(5).

      # The loopback network interface
#      auto lo
#      iface lo inet loopback

      # The primary network interface
#      auto eth0
#      iface eth0 inet dhcp
      # Example to keep MAC address between reboots
      #hwaddress ether DE:AD:BE:EF:CA:FE

      # To setup wifi use nmtui to add or edit connections instead

      # Ethernet/RNDIS gadget (g_ether)
      # Used by: /opt/scripts/boot/autoconfigure_usb0.sh

 #     auto usb0
 #     iface usb0 inet static
 #     address 192.168.7.2
#      netmask 255.255.255.252
#      network 192.168.7.0
#      gateway 192.168.7.1
      
- name: remove unneeded files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apache2/
    - /root/.c9
    - /usr/lib/node_modules
    - /usr/local/lib/node_modules
    - /var/lib/cloud9
    - /var/cache/doc*

- name: create dogtag
  file:
    path: /etc/dogtag
    state: touch

- name: get date
  command: 'date'
  register: build_date

- name: write dogtag
  lineinfile:
    line: '{{ version }} {{ build_date }}'
    state: present
    path: /etc/dogtag


- name: remove hosts entry
  lineinfile:
    path: /etc/hostname
    line: arm
    state: absent

- name: set hostname
  lineinfile:
    path: /etc/hostname
    line: refactor
    state: present

- name: set host entry
  lineinfile:
    path: /etc/hosts
    line: '127.0.1.1 refactor refactor.local'
    state: present

- name: set root password
  shell:
    cmd: "echo 'root:kamikaze' | chpasswd"

- name: force user to change password on first login
  shell:
    cmd: "chage -d 0 root"

- name: create issue and issue.net file
  file:
    path: '{{ item }}'
    state: touch
  with_items:
   - /etc/issue
   - /etc/issue.net

- name: write issue and issue.net
  blockinfile:
    path: '{{ item }}'
    state: present
    block: |
      "{{ version }}
      Built from an rcn-ee.net console image.

      Check that nothing is printing before any intensive operation!"
  with_items:
    - /etc/issue.net
    - /etc/issue
