---
- name: create local apt conf
  file: 
    path: /etc/apt/apt.conf.d/99local
    owner: root
    group: root
    state: touch
    
- name: disable install recommends
  lineinfile:
    path: /etc/apt/apt.conf.d/99local
    regexp: 'Install-Recommends'
    line: 'APT::Install-Recommends "false";'
    
- name: disable install suggestions
  lineinfile:
    path: /etc/apt/apt.conf.d/99local
    regex: 'Install-Suggests'
    line: 'APT::Install-Suggests "false";'
    
- name: remove grub
  apt:
    name: grub-efi-arm
    state: absent
    
- name: remove login info
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/issue.net
    - /etc/issue
    
- name: upgrade packages
  apt:
    upgrade: dist
    
- name: remove unneeded packages
  apt:
    pkg:
    - linux-image-*
    - linux-headers-*
    - apache2
    - apache2-bin
    - apache2-data
    - apache2-utils
    - hostapd
    - libgtk3-common
    state: purge
    autoremove: yes

- name: disable rproc overlay
  lineinfile:
    path: /boot/uEnv.txt
    regex: '/lib/firmware/AM335X-PRU-RPROC'
    line: '#uboot_overlay_pru=/lib/firmware/AM335X-PRU-RPROC'

- name: enable uio overlay
  lineinfile:
    path: /boot/uEnv.txt
    regex: '/lib/firmware/AM335X-PRU-UIO'
    line: 'uboot_overlay_pru=/lib/firmware/AM335X-PRU-UIO'

- name: fix double hash
  lineinfile: 
    path: /boot/uEnv.txt
    regex: '##uboot'
    line: '#uboot'

- name: update RCN scripts
  command:
    chdir: /opt/scripts/tools
    cmd: 'git pull'

- name: update kernel using RCN scripts
  command:
    chdir: /opt/scripts/tools
    cmd: 'FORCEMACHINE=TI_AM335x_BeagleBoneBlack sh update_kernel.sh --lts-4_19 --ti-kernel'

- name: install debconf-utils
  apt:
    name: debconf-utils
    state: latest

- name: configure ipv4
  command:
    cmd: 'echo "iptables-persistent     iptables-persistent/autosave_v4 boolean true" | debconf-set-selections'

- name: configure ipv6
  command:
    cmd: 'echo "iptables-persistent     iptables-persistent/autosave_v6 boolean true" | debconf-set-selections'

- name: add thing printer debian repository
  apt_repository:
    repo: deb [arch=armhf] http://kamikaze.thing-printer.com/ubuntu/ xenial main
    state: present

- name: add thing printer key
  apt_key:
    url: http://kamikaze.thing-printer.com/ubuntu/public.gpg
    state: present

- name: update package list
  apt:
    update_cache: yes

- name: install packages
  apt:
    pkg:
    - unzip
    - iptables
    - iptables-persistent
    - python-pip
    - python-pip3
    - python-dev
    - python-virtualenv
    - libyaml-dev
    - libavahi-compat-libdnssd1
    - libnss-mdns
    - screen
    - byobu
    - htop
    - unzip
    - cpufrequtils
    - f2fs-tools
    - parted
    - python-parted
    - network-manager
    - pkg-config
    - python3-dev
    - network-manager
    - libcairo2-dev
    - libgirepository1.0-dev
    - python3-gi-cairo
    - libcairo2-dev
    - pkg-config
    - python3-dev
    - gir1.2-gtk-3.0
    state: latest
    autoremove: yes
    autoclean: yes

- name: install pip libs
  command:
    cmd: "yes | pip install setuptools wheel pycairo PyGObject"
- name: install pip3 libs
  command:
    cmd: "yes | pip3 install setuptools wheel pycairo PyGObject"

- name: enable netfilter
  service:
    name: netfilter-persistent
    enabled: yes

- name: enable root login via ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: 'PermitRootLogin'
    line: 'PermitRootLogin yes'

- name: disable the power button
  lineinfile:
    path: /etc/systemd/logind.conf
    regex: 'HandlePowerKey'
    line: 'HandlePowerKey=ignore'

- name: disable wireless power management
  file:
    path: /etc/pm/sleep.d/wireless
    state: touch

- name: update dhcp
  lineinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    regex: 'dhcp'
    line: 'dhcp=internal'

- name: setup network interfaces file
  blockinfile:
    path: /etc/network/interfaces
    block: |
      # This file describes the network interfaces available on your system
      # and how to activate them. For more information, see interfaces(5).

      # The loopback network interface
      auto lo
      iface lo inet loopback

      # The primary network interface
      auto eth0
      iface eth0 inet dhcp
      # Example to keep MAC address between reboots
      #hwaddress ether DE:AD:BE:EF:CA:FE

      # To setup wifi use nmtui to add or edit connections instead

      # Ethernet/RNDIS gadget (g_ether)
      # Used by: /opt/scripts/boot/autoconfigure_usb0.sh

      auto usb0
      iface usb0 inet static
      address 192.168.7.2
      netmask 255.255.255.252
      network 192.168.7.0
      gateway 192.168.7.1
      
- name: remove unneeded files
  file:
    path: "{{ item }}"
    state: absent
    recurse: yes
  with_items:
    - /etc/apache2/
    - /root/.c9
    - /usr/lib/node_modules
    - /usr/local/lib/node_modules
    - /var/lib/cloud9
    - /var/cache/doc*

- name: create dogtag
  file:
    path: /etc/kamikaze-release
    state: file

- name: get date
  command: 'date'
  register: build_date

- name: write dogtag
  lineinfile:
    line: '{{ version }} {{ build_date }}'
    state: present
    path: /etc/kamikaze-release
    
- name: write LCD screen rules
  lineinfile:
    path: /etc/udev/rules.d/80-lcd-screen.rules
    line: '{{ item }}'
    state: present
  with_items:
    - "SYSFS{idVendor}==\"0eef\", SYSFS{idProduct}==\"0001\", KERNEL==\"event*\",SYMLINK+=\"input/touchscreen_eGalaxy3\""
    - "KERNEL==\"uinput\", GROUP=\"wheel\", MODE:=\"0660\""

- name: remove hosts entry
  lineinfile:
    path: /etc/hosts
    regex: arm
    state: absent

- name: set hostname
  lineinfile:
    path: /etc/hosts
    line: '127.0.1.1 Kamikaze Kamikaze.local'
    state: present

- name: set root password
  user:
    name: root
    password: kamikaze
    shell: /bin/bash
    generate_ssh_key: yes

- name: write issue and issue.net
  blockinfile:
    path: '{{ item }}'
    state: present
    block: |
      "{{ version }}
      Built from an rcn-ee.net console image.

      Check that nothing is printing before any intensive operation!"
  with_items:
    - /etc/issue.net
    - /etc/issue
