---
- name: clone klipper from the repository
  git: 
    repo: https://github.com/KevinOConnor/klipper
    dest: /usr/src/klipper
    update: yes
    clone: yes

- name: adjust ownership of klipper source
  file:
    path: /usr/src/klipper
    owner: octo
    group: octo
    recurse: yes

- name: install system klipper dependencies
  apt:
    pkg:
      - python-virtualenv
      - virtualenv
      - python-dev
      - libffi-dev
      - build-essential
      - libncurses-dev
      - libusb-dev
      - stm32flash
      - libnewlib-arm-none-eabi
      - gcc-arm-none-eabi
      - binutils-arm-none-eabi
      - gcc-pru
    state: latest
    update_cache: yes

- name: install pip klipper dependencies
  pip:
    virtualenv: /usr/local/klipper/
    virtualenv_python: python2.7
    requirements: /usr/src/klipper/scripts/klippy-requirements.txt

- name: compile binary blobs for klippy
  shell:
    cmd: "cd /usr/src/klipper ; cp {{ item }} .config ; make flash"
  with_items:
    - "{{ role_path }}/files/pru_config"
    - "{{ role_path }}/files/linux_config"

- name: copy klipper service
  copy:
    src: "{{ role_path }}/files/klipper.service"
    dest: /lib/systemd/system/klipper.service

- name: enable klipper service
  service:
    name: klipper
    enabled: yes


- name: make klipper config directory
  file:
    path: /etc/klipper
    state: directory
    owner: octo
    group: octo

- name: create klipper config file
  copy:
    src: /usr/src/klipper/config/generic-replicape.cfg
    dest: /etc/klipper/printer.cfg
    owner: octo
    group: octo

- name: install PRU start scripts
  copy:
    src: "{{ role_path }}/files/klipper_pru"
    dest: /etc/init.d/klipper_pru

- name: update services
  shell:
    cmd: "update-rc.d klipper_pru defaults"

- name: copy systemd klipper_pru file
  copy:
    src: "{{ role_path }}/files/klipper_pru.service"
    dest: /lib/systemd/system/klipper_pru.service

- name: enable systemd klipper_pru
  service:
    name: klipper_pru
    enabled: yes

- name: create udev rule file
  file:
    path: /etc/udev/rules.d/pru.rules
    state: touch

- name: place Klipper-friendly config for octoprint in place
  copy:
    src: "{{ role_path }}/files/octoprint_config.yaml"
    dest: /home/octo/.octoprint/config.yaml
    owner: octo
    group: octo
